### ISSUE TITLE
возможный баг, максимальное число адресов в мультиподписи

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#107]
Когда делал https://github.com/novacoin-project/novacoin/pull/106 , заметил комментарий:
```c
// Biggest 'standard' txin is a 3-signature 3-of-3 CHECKMULTISIG
// pay-to-script-hash, which is 3 ~80-byte signatures, 3
// ~65-byte public keys, plus a few script ops.
 if (txin.scriptSig.size() > 500)
{
    strReason = "scriptsig-size";
    return false;
}
```
Но в RPC createmultisig  нет никаких ограничений при создании адреса, как впрочем и в GUI.
Возможно следует добавить ограничения при создании адреса, что пользователь не мог создать такой адрес, транзакции с которого не будут приняты...

**Comment by CryptoManiac** [comment]
Давно известная "фича", в общем-то. Самым очевидным решением является ограничение M и N до 3, всё равно в стандартной транзакции больше быть не может.

**Comment by fsb4000** [comment]
3 и 3 это я как понимаю худший случай, когда public key используется несжатый. По умолчанию public key генерируется сжатый.(У меня у всех адресов, "iscompressed" : true) То есть и 4-4 пройдёт, 4 x 80 + 4 x 33 = 452 ) Но если такие проверки сложно сделать, можно ограничить и 3-3 
В любом случае нужно будет написать инструкцию в doc, где описать какие файлы изменить в клиенте, чтобы можно было отправить "нестандартную" транзакцию(если кто-то уже создал адрес с мультиподписью с большим количеством адресов и перевёл туда монеты). Вроде бы сеть должна принять такой блок? (В **CBlock::CheckBlock** для проверки транзакций я вижу только **CTransaction::CheckTransaction()**, а там scriptSig.size проверяется только для coinbase транзакции
```c
if (IsCoinBase())
    {
        if (vin[0].scriptSig.size() < 2 || vin[0].scriptSig.size() > 100)
            return DoS(100, error("CTransaction::CheckTransaction() : coinbase script size is invalid"));
    }
```
А есть ли ограничения для "нестандартных" multisig транзакций? Вроде бы находил на bitcointalk'е что 520 байт ограничение на ограничений redeemscript, которое даёт ограничение на 14 сжатых public key и 7 несжатых.  Это вроде в файле **script.h** :
```c
static const unsigned int MAX_SCRIPT_ELEMENT_SIZE = 520; // bytes
```
Больше нет ограничений?

**Comment by CryptoManiac** [comment]
Ещё 10 килобайт на скрипт в целом. В целом, неважно каково реальное ограничение на размер в данном случае, скорее важно то что клиент не должен позволять юзеру создавать нестандартную транзакцию штатными средствами.

```чтобы можно было отправить "нестандартную" транзакцию```
Её отправить в любом случае нельзя, остальные клиенты нестандартную транзакцию не примут. Нестандартные транзакции могут быть приняты только в составе уже сгенерированных блоков.

**Comment by fsb4000** [comment]
>чтобы можно было отправить "нестандартную" транзакцию

**CryptoManiac:**
>Её отправить в любом случае нельзя, остальные клиенты нестандартную транзакцию не примут. Нестандартные транзакции могут быть приняты только в составе уже сгенерированных блоков.

Да, это я неправильно выразился. Я имел ввиду такую инструкцию, чтобы пользователи смогли самостоятельно упаковать в блок и перевести средства с такого multisig адреса. То есть нужно чтобы в mempool транзакция вошла, не не слать её другим пирам, чтобы они не забанили узел...

**Comment by fsb4000** [comment]
Может имеет смысл увеличить стандартный scriptSig.size до 1650, тогда можно будет использовать до 15-15 multisig адреса, и проверка при создании адреса будет лёгкой, просто  проверить что redeemscript < 520 байт ??
Примерно тоже самое сделали в bitcoin, начиная с версии 0.10
https://github.com/bitcoin/bitcoin/commit/4d79098ad548874ca6e4c09d873fc2f481e6edb4

**Comment by 0xDEADFACE** [comment]
Смержить имеет смысл, но в краткосрочной перспективе никакого эффекта от этого не будет.

**Comment by fsb4000** [comment]
Нужно ещё добавить проверку на redeemScript size в GUI.(в фукнцию void MultisigDialog::on_createAddressButton_clicked() , в файле **src\qt\multisigdialog.cpp**)
Пока склоняюсь просто к такому:
```c
if (script.size() > MAX_SCRIPT_ELEMENT_SIZE)
    {
        QMessageBox::warning(this, tr("Error"), QString("redeemScript exceeds size limit: %1 > %2").arg(script.size()).arg(MAX_SCRIPT_ELEMENT_SIZE), QMessageBox::Ok);
        return;
    }
```
Но возможно для GUI нужно более подробное описание ошибки, чем "redeemScript exceeds size limit: %1 > %2" То есть ещё написать "уменьшите число используемых адресов, чтобы уменьшить размер redeemScript size"
