### ISSUE TITLE
не начинается POS майнинг

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#108]
**Victor1739:**
>Добрый вечер
```c
mainnet
unsigned int nStakeMinAge = 60; // 1 минута
```
Прошли почти сутки, нет ни одного POS блока.
testnet также POS блоков не выдает
Клиент пишет при наведении на молоточки "нет подходящих транзакций для майнинга".
В чем может быть причина?
Собрал последнюю версию NVC с измененными портами и удаленными кроме нулевого блока checkpoints (больше изменений нет).
Запустил -testnet на 2 ПК, сгенерировал 60+ POW блоков. Несколько часов ожидал POS блоков - их нет.
Перевел дату на обоих ПК в будущее, транзакции с большим весом также не дают POS блоков.
Молоточки показывают "Нет подходящих транзакций для майнинга".
Подскажите пожалуйста, что я упускаю?

От себя добавлю: То что POS блоков нет, это ладно. Может сильно не везёт и
```c
bnTargetProofOfStake >= CBigNum(hashProofOfStake)
```
не выполняется. Но почему  молоточки показывают нет подходящих транзакций? Возможно есть какой-то баг в работе молоточков...
P.S. я POS блоки находил и в testnet и в mainnet...
P.P.S. А как метки на гитхабе добавлять к проблемам, типа низкий приоритет или наоборот высокий приоритет, как в Bitcoin репозитарии?

**Comment by 0xDEADFACE** [comment]
Ожидаемое поведение. Помимо возраста нужны ещё и подтверждения. 

nCoinbaseMaturity * 10, что дает 5200 подтверждений в основной сети или 100 подтверждений в тестовой.

**Comment by fsb4000** [comment]
**Victor1739:**
>Спасибо за подсказку.
Сейчас блоки в  testnet имеют больше 150 подтверждений. Молоточки показывают "нет подходящих транзакций".
Собрал клиент с int nCoinbaseMaturity = 1. Молоточки продолжают показывать "нет подходящих транзакций".
![molotok](http://i.imgur.com/Jea3lGM.png)

**Comment by 0xDEADFACE** [comment]
На самом деле не совсем понимаю, в чем смысл модификации базовых переменных.

Интересно в общем, первое что приходит в голову это запустить клиент с ключом -debug и посмотреть, что майнер в логи пишет.

**Comment by fsb4000** [comment]
**Victor1739:**
>Базовые параметры поменял для удобства тестирования после того как имея 150 подтверждений подходящие транзакции не нашлись клиентом.
Запустил с ключами -debug -printcoinstake
```
ThreadOpenAddedConnections started
ThreadOpenConnections started
trying connection 176.53.12.90 lastseen=0.0hrs
ThreadMessageHandler started
ThreadStakeMinter started
Flushed 3 addresses to peers.dat  20ms
ipcThread started
connected 176.53.12.90
send version message: version 60016, blocks=303, us=0.0.0.0:0, them=176.53.12.90:52177, peer=176.53.12.90:52177
sending: version (102 bytes)
received: version (102 bytes)
Added time data, samples 2, offset +27 (+0 minutes)
sending: verack (0 bytes)
sending: getaddr (0 bytes)
sending: getblocks (677 bytes)
receive version message: version 60016, blocks=303, us=176.53.12.54:18366, them=176.53.12.90:52177, peer=176.53.12.90:52177
received: verack (0 bytes)
received: getblocks (677 bytes)
getblocks -1 to 00000000000000000000 limit 500
Stake miner: 0 meta items loaded for 283 coins
received: addr (31 bytes)
```
Перевел дату на 2 суток вперед на 2-х ПК, подходящие транзакции не находит:
```
ThreadOpenConnections started
trying connection 176.53.12.117 lastseen=0.0hrs
ThreadMessageHandler started
ThreadStakeMinter started
Flushed 3 addresses to peers.dat  0ms
ipcThread started
connected 176.53.12.117
send version message: version 60016, blocks=303, us=0.0.0.0:0, them=176.53.12.117:52177, peer=176.53.12.117:52177
sending: version (102 bytes)
received: version (102 bytes)
Added time data, samples 2, offset +27 (+0 minutes)
sending: verack (0 bytes)
sending: getaddr (0 bytes)
sending: getblocks (677 bytes)
receive version message: version 60016, blocks=303, us=176.53.12.116:18417, them=176.53.12.117:52177, peer=176.53.12.117:52177
received: verack (0 bytes)
received: getblocks (677 bytes)
getblocks -1 to 00000000000000000000 limit 500
received: addr (31 bytes)
received: addr (31 bytes)
Stake miner: 0 meta items loaded for 283 coins
ResendWalletTransactions()
```

P.S. если проблема не решится, попросил Victor1739'а присоединиться сюда в github

**Comment by 0xDEADFACE** [comment]
Судя по логу, транзакции вообще не были выбраны. Суд по всему, не происходит генерация StakeModifier из-за того, что сгенерировано слишком мало блоков.

https://github.com/novacoin-project/novacoin/blob/master/src/wallet.cpp#L1865

Я бы оставил PoW майнер подумать некоторое время и забыл про него, сам так делал при проверках на тестнете.

**Comment by fsb4000** [comment]
**Victor1739:**
>Спасибо за помощь. Примерно после 420 блока включились молоточки, после перевода даты на 3 суток вперед начался POS майнинг.

**Comment by Melaniaio** [comment]
https://github.com/novacoin-project/novacoin/issues/108
