### ISSUE TITLE
Описание транзакций добытых майнингом

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#117]
**Victor1739**:
>Кажется, небольшой баг интерфейса
![bug](http://i.imgur.com/LiC5WOI.png)
Монеты получены майнингом, им нужно не 6 а 520 подтверждений

>Подскажите пожалуйста в двух словах, за что отвечает параметр?
unsigned int nModifierInterval = 6 * 60 * 60;

**Comment by CryptoManiac** [comment]
Это интервал пересчета модификатора stake kernel.

**Comment by fsb4000** [comment]
А с интерфейсем так и должно быть?
Если да, то можно закрыть issue...

**Comment by CryptoManiac** [comment]
Строго говоря, такого быть не должно. Однако, это во всех сатоши клиентах является своего рода стандартной "фичей". Надо для generated транзакций увеличивать количество требуемых подтверждений в подсказке, конечно... Тернарным оператором, как вариант. Завтра закоммичу патч, думаю.

**Comment by 0xDEADFACE** [comment]
А то что-то завтра у тебя затянулось слегка )

**Comment by CryptoManiac** [comment]
Да забыл что-то.
