### ISSUE TITLE
Где файл licence.txt?

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#124]
> Распространяется на правах лицензии MIT/X11, см. файл license.txt или http://www.opensource.org/licenses/mit-license.php

Но у нас в архивах на sourceforge.net только файлы **novacoin-qt** и **novacoind**
Предлагаю в будущих релизах включать и файл с лицензией в архивы.
P.S. у биткоина есть файл COPYING.txt  в установщике...

**Comment by CryptoManiac** [comment]
Раньше клался, потом что-то забыли о нем. Вообще, думаю что хорошо бы встроить этот текст в виде отдельной формы в сам клиент... Как вариант, вызываемой по специальному ключу или по кнопке в AboutDialog. Тогда и лишних файлов будет не нужно.
