### ISSUE TITLE
Сортировка транзакций по сумме не работает

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#130]
**Victor1739:**
>Сортировка транзакций по сумме не корректно работает, пример сортировки по убыванию.
```
3.43
3.33
3.23
0.001
3.13
3.03
```
Маленькие суммы транзакций игнорируются при сортировке и они остаются на своих местах.

Подтверждаю, у меня тоже сортировка не работает.
Вот так вывелось
![сортировка](http://i62.tinypic.com/2wovnr8.jpg)

**Comment by fsb4000** [comment]
Разобрался в чём дело.
В этом коммите (https://github.com/novacoin-project/novacoin/commit/de1077975fe6f8b0be3982b0e2708f0ae5c9cabe) сделали чтобы сортировка во вкладке транзакции была всегда по дате, а не по любому столбцу.
если убрать комментарий с этой строки(в файле transactionview.cpp)
```
filter->setSortRole(Qt::EditRole);
```
и закоментировать эту строку
```
 filter->setSortRole(TransactionTableModel::DateRole);
```
то сортировка должна начать работать по любому столбцу.
Есть ли какой-то смысл ограничивать сортировку только по дате?

**Comment by CryptoManiac** [comment]
@fsb4000 

>> Есть ли какой-то смысл ограничивать сортировку только по дате?

Возможно, это связано с отображением орфанов на главной странице.

**Comment by fsb4000** [comment]
**CryptoManiac:**
>Возможно, это связано с отображением орфанов на главной странице.

Посмотрим как будет работать https://github.com/novacoin-project/novacoin/pull/131 . Если будут какие-тоо проблемы с отображением, то откатим...
