### ISSUE TITLE
О MAX_MONEY

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#132]
**Victor1739:**
>Переменная MAX_MONEY не работает. Мне было интересно поведение бумажника при генерации монет сверх возможного количества. Монеты можно майнить когда их больше MAX_MONEY.

Может удалить из Readme
**~ 2 billion total coins**
чтобы не вводило в заблуждение пользователей?? Или как-то понятнее расписать, что MAX_Money это ограничение на количество монет во входах/выходах в одной транзакции, а не общее число монет...

**Comment by CryptoManiac** [comment]
Предел на реальное количество монет в системе есть, но мы неспособны сказать заранее, каким он будет и когда. Так же как неспособны сказать, сколько в итоге будет добыто золота или урана к моменту истощения всех существующих месторождений. Предел текущего количества монет в системе определяется не какими-то константами в коде, а текущей активностью всех её пользователей, о чем в описании алгоритма эмиссии указано. Мы ограничиваем эмиссию не категориями "больше нельзя", а "нужно генерировать меньше/больше, потому что изменились условия". :)

Но тут дело в том, что есть люди, которым нужно четкое число, и им безразлично если оно будет заведомо неправильным, необоснованным и очень далеком от истины. Эта переменная является именно такой условностью и в реальной ситуации с высокой вероятностью не будет достигнута никогда. Она была нужна именно в таком виде, потому что пришедшим из биткоина или лайткоина нужно увидеть что-то привычное, чего в нашей сети просто быть не может в виду того, что отсутствие жесткого ограничения эмиссии является необходимостью. 

Так что убрать мы можем, конечно, но что тогда написать вместо этого... Как вариант, писать там текущее количество сгенерированных монет, и обновлять его с каждым тегом.

**Comment by 0xDEADFACE** [comment]
Давайте уберем эту строку совсем, чтобы не вводила в заблуждение тех, кто смотрит поверхностно. Ну или на самом деле, текущее количество монет там писать.
