### ISSUE TITLE
В coincontrol первый стоблец "1"

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#135]
Только при компиляции с помощью Qt4, при компиляции с помощью Qt5 отображается нормально.
Вот так отображается на Windows сборках с sourceforge:
![1](http://i58.tinypic.com/34sjjp2.jpg)

**Comment by fsb4000** [comment]
В дизайнере отображается тоже нормально:
![designer](http://i58.tinypic.com/15raw53.jpg)

Да и коде нет изменений текста этого столбца... Баг Qt4?

**Comment by fsb4000** [comment]
В старых версиях точно так же. По крайней мере в версиях старше **novacoin-nosetup-0.4.4.6-update7-win32-amd64**

**Comment by fsb4000** [comment]
Если у кого-то есть решение лучше чем https://github.com/novacoin-project/novacoin/pull/136 , то не стесняйтесь :)

**Comment by 0xDEADFACE** [comment]
Действительно, весьма похоже на баг Qt4. Устранять особого смысла не имеет, потому что собираться в дальнейшем будут сборки с Qt5. Но может кому нужно именно Qt4, так что мержим.
