### ISSUE TITLE
Улучшение: Создавать novacoin.conf по умолчанию

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#143]
Как вы относитесь к такому патчу. При запуске клиент проверяет есть ли файл novacoin.conf и если файла нет, то создаётся файл со значениями по умолчанию. 
Например такие значения
```
rpcuser=user 
rpcpassword=<случайная последовательность символов 15 значной длины>
rpcport=8344
port=7777
server=1
daemon=1
rpcallowip=localhost
testnet=0
```
Причины для этого патча:
1)https://bitcointalk.org/index.php?topic=911645.msg10253537#msg10253537
2)случай угона монет через RPC
3)просто новички для пробы соло майна ,например, могут выставить только 
```
user=user
password=password
```
и оставить так....

**Comment by CryptoManiac** [comment]
Лично я считаю, что автогенерация с длинным паролем и, опционально, со случайным именем пользователя была бы более чем полезной. Вот только сервер и демон по умолчанию лучше закомментировать... 

Ведь основная причина проблемы не в паролях и даже не в самих настройках. Она в том, что новички сталкиваются с когнитивным диссонансом, когда нужно файл создать, предпочитая копипаст в качестве решения.

**Comment by fsb4000** [comment]
Да, хорошо демон и сервер закоментировать, и добавить коментарии для чего эти функции(на английском, или на двух языках?)
Ещё какие-нибудь опции добавить(возможно в комментариях)?
Я заметил автосоздание .conf файла в https://github.com/jl777/btcd , так что думаю на выходных без проблем получится перенести в NVC

**Comment by Foxcool** [comment]
Теоретически, можно даже дать настрйки менять неосиляторам в  гуях в будущем.
