### ISSUE TITLE
Каталог Doc

### ISSUE THREAD

**Issue by svost** [novacoin-project/novacoin#161]
Есть предложение добавлять к файлам признаки _RU _EN. Или как правильно поступают в подобной ситуации?

**Comment by fsb4000** [comment]
Не знаю как правильно. Может создать папки RU, EN и т.д.? И потом добавлять инструкции на других языках если кто-то переведёт/просто напишет на другом языке...

**Comment by CryptoManiac** [comment]
Вообще, обычно это решают префиксами. Подкаталоги создают, если документации очень много.

**Comment by svost** [comment]
Предлагаю назвать русскоязычные фалы подобным образом:
crosscompiling_building Windows binary under Unix_RU.txt (на текущий момент 5 файлов).
Приставку _EN считать по умолчанию и не указывать. После внесения изменений issue можно закрыть.
