### ISSUE TITLE
Баг: Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

### ISSUE THREAD

**Issue by fsb4000** [novacoin-project/novacoin#164]
В Linux Mint 17.1(интерфейс MATE) при запуске novacoin-qt из консоли и нажатии на чекбоксы в окне "Настройки->Опции" выдаются ошибки в консоль:
Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed

Насколько я понял это проблема GTK, если чекбоксам сменить стиль на "Cleanlooks" или "Windows" то ошибки в консоли не будет.

Важно: Ошибки только выводятся в консоль, на работоспособность приложения не влияет. 
Следует ли менять стили кнопкам, если да то какой стиль выбирать?

Вот такая же проблема в интернете: http://www.linux.org.ru/forum/development/10225544

**Comment by fsb4000** [comment]
у Bitcoin-qt такая же ошибка...

**Comment by fsb4000** [comment]
Вот как выглядят окна с оригинальным и изменённым стилем:
![original](http://i59.tinypic.com/iygewj.png)
![changed](http://i61.tinypic.com/auxs0n.png)

**Comment by 0xDEADFACE** [comment]
Такие вещи проскакивают во многих приложениях, например qtcreator тот же.

**Comment by fsb4000** [comment]
Ладно, не будем править в основном коде, но я оставлю тут код для смены стилей у кнопок(если кто-то захочет изменить для себя).
В файле optionsdialog.cpp добавить
```c
#include <QStyleFactory>
```
и в конструкторе, после ui->setupUi(this);, добавить
```c
    ui->mapPortUpnp->setStyle(QStyleFactory::create("Windows"));
    ui->bitcoinAtStartup->setStyle(QStyleFactory::create("Windows"));
    ui->detachDatabases->setStyle(QStyleFactory::create("Windows"));
    ui->connectSocks->setStyle(QStyleFactory::create("Windows"));
    ui->connectTor->setStyle(QStyleFactory::create("Windows"));
    ui->minimizeOnClose->setStyle(QStyleFactory::create("Windows"));
    ui->minimizeToTray->setStyle(QStyleFactory::create("Windows"));
    ui->displayAddresses->setStyle(QStyleFactory::create("Windows"));
    ui->coinControlFeatures->setStyle(QStyleFactory::create("Windows"));
```
