### ISSUE TITLE
Non-genesis transaction inaccessible to novacoind getrawtransaction

### ISSUE THREAD

**Issue by dlio** [novacoin-project/novacoin#19]
novacoind getblockbynumber 10022
{
    "hash" : "2f942cad0019a69cc83e9cfbdb65dcad7f8ed81eca2b027b2fa490f71f75e7af",
    "size" : 1146,
    "height" : 10022,
    "version" : 2,
    "merkleroot" : "6950c20fca1f4b3091cc274ba4c0cc37e86927431814e9a927cca81ab50e5441",
    "time" : "2013-03-12 06:49:35 UTC",
    "nonce" : 0,
    "bits" : "1e0fffff",
    "difficulty" : 0.00024414,
    "mint" : 0.25000000,
    "previousblockhash" : "0000000000e5885d4087ab52b37d81baf28b4b58231402cfd9fe6d4946edacf8",
    "nextblockhash" : "00000000072940ff4f46eabace834d681fd20488034517acdc13c8ec7b2771d3",
    "flags" : "[b]proof-of-stake[/b] stake-modifier",
    "proofhash" : "000018d0aa7d744d1c92e2ed0d3b9b2ea313e4a6e72fc7013b6bbebbd414eaf9",
    "entropybit" : 1,
    "modifier" : "6204915d04d03e0d",
    "modifierchecksum" : "de2ba9c9",
    "tx" : [
        "7473c894134d83bf4a0a5207310520c12edb9bf69411e27b672d77a847d553a0",
        "01c4dea3d857183a43c126cf34f232bfd2453d3f8f78195b211d9e7a3544a31d",
        "578f2a5464c6f4beade6ea0627c4dc4f3f486d52affe3b24e3f3db349b1d7582",
        "41de352ef0b8f1c3cd2dcf3837c4429a43aaebb8cda12a608f8b3dbd896dc76b",
        "fb725604b226f8e59aeb07ec21c775f2bd8e3d2033ed46f4562e71b43427cfbf"
    ]
}

`novacoind getrawtransaction 7473c894134d83bf4a0a5207310520c12edb9bf69411e27b672d77a847d553a0 1` 
results in:
error: {"code":-5,"message":"No information available about transaction"}

There was some mention on the forums of nested child blocks but I'm afraid I don't understand what happened here that made this coinbase transaction inaccessible to getrawtransaction.  Does anyone have a solution for this error?

Relevant reference: 
https://bitcointalk.org/index.php?topic=143221.msg1608065#msg1608065

**Comment by Infernoman** [comment]
Just wondering if anything has been done for this issue? i recently rebased to novacoin for sembro-token, and have been having troubles getting a block explorer online because of this.

**Comment by CryptoManiac** [comment]
Hi, @Infernoman 

WIth notorious exception for timestamp, the Proof-of-Stake coinbase doesn't contain any sensitive information. That's why Proof-of-Stake coinbases are ignored by ConnectBlock  function.

**Comment by Infernoman** [comment]
Thank you for such a quick reply ! that would be a viable option for dev's but unfortunately most people around lately (including myself) arent very experienced. I did manage to get swapped over okay. and i completely understand why they are being cut out. i have also tried to tell this to the block explorer i was working with. Would you be able to give me an idea of where these transactions are pruned from the database in novacoin or perhaps take a look at my current source to help me keep track of these coinbase transactions in sembro token? i know this is big to ask of another developer. but I myself have no physical connection to sembro other than i own some. I went through with a hard fork on sembro, with the owners permission. but with the troubles i've been having i would just like to include them if possible
