### ISSUE TITLE
Новый блок и 0 баланс в нем

### ISSUE THREAD

**Issue by gades** [novacoin-project/novacoin#204]
Если майнить в режиме соло и в блоке указать выплату на несколько адресов (пример p2pool) и один баланс равен 0, то в найденом блоке будет и перевод =0 
![screen shot 2015-04-12 at 09 07 41](https://cloud.githubusercontent.com/assets/4200730/7104563/725195fa-e0f3-11e4-920a-1b07ef98f1a2.png)
Но если смотреть информацию о блоке, то видна одна сумма https://explorer.novaco.in/tx/d035f91cf9789114b7eefbfd926704fc699d3069a388d42fdf8dcf9e50355f6e
Есть ли смысл включать в блок 0й перевод? 

Для воспроизведения указанной проблемы, необходимо взять p2pool отредактировать файл p2pool/p2pool/networks.py
PERSIST=False,
BOOTSTRAP_ADDRS=''.split(' '),

p2pool/p2pool/data.py
DONATION_SCRIPT - указать public key в hex (можно не менять и 0 будет идти на тот адрес)

Ну естественно и запустить с --give-author=0

**Comment by gades** [comment]
Да, но вот он теперь постоянно лежит глаз в разделе "Mining" (может есть смысл подправить тут, чтобы отображались балансы больше 0)
![screen shot 2015-04-25 at 20 07 21](https://cloud.githubusercontent.com/assets/4200730/7333848/bdbfb1d2-eb86-11e4-9412-7bc60d1f6bff.png)

**Comment by CryptoManiac** [comment]
Да, пожалуй имеет смысл ограничить выборку таким условием.  А если точнее, то выше 0.01. Потому что выходы с меньшей суммой не могут генерировать блоки.
