### ISSUE TITLE
Mining Novacoin?

### ISSUE THREAD

**Issue by AlexKhodaverdian** [novacoin-project/novacoin#370]
I'm new to altcoin development, so I preface this question by saying it may be a dumb question.

I noticed novacoin has no setgenerate for mining. How would one go about mining novacoin from just downloading the node code?

**Comment by AlexKhodaverdian** [comment]
Nvm resolved

**Comment by oleumobi** [comment]
Hello - I have same question. I have two nodes up and running. How do I kick off mining ? Thanks for help in advance.

**Comment by douglasdeodato** [comment]
how did u solve AlexKhodaverdian ?

**Comment by fiksn** [comment]
I am asking myself the same. How can you effectively test stuff in `-regtest` mode w/o something similar to `setgenerate`?
