### ISSUE TITLE
error: 'intro.moc' file not found

### ISSUE THREAD

**Issue by kenneth** [novacoin-project/novacoin#373]
how to generate intro.moc?

```
/novacoin/src/qt/intro.cpp:54: error: 'intro.moc' file not found
#include "intro.moc"
         ^~~~~~~~~~~
```

**Comment by CryptoManiac** [comment]
*.moc files are generated automatically by the meta object compiler, while building Qt forms. 

If this doesn't happen for some reason then you can force them build manually through invoking moc tool directly.

**Comment by nerdlabs001** [comment]
> how to generate intro.moc?
> 
> ```
> /novacoin/src/qt/intro.cpp:54: error: 'intro.moc' file not found
> #include "intro.moc"
>          ^~~~~~~~~~~
> ```

I had the same problem when trying to build from within qt creator on another coin (how i ended up here) . I ran make clean , then cleaned out my build folder and the obj folder , re ran qmake and it built without issue . qt tends to not regenerate files that are already in existence

**Comment by saa-cryp** [comment]
[options
](url)
