### ISSUE TITLE
Problem starting wallet on Ubuntu

### ISSUE THREAD

**Issue by mocap3069** [novacoin-project/novacoin#374]
I am trying to start a newly installed wallet on an Ubuntu server but getting this error:
mocap3069@ubuntu-s-2vcpu-4gb-sfo2-01:~/novacoin/src$ ./novacoind

************************
EXCEPTION: N5boost12interprocess22interprocess_exceptionE
Permission denied
novacoin in AppInit()

terminate called after throwing an instance of 'boost::interprocess::interprocess_exception'
  what():  Permission denied
Aborted (core dumped)
Any suggestions?

**Comment by CryptoManiac** [comment]
Looks like either your data directory or home folder have no read no write permissions. This causes daemon to crash while trying to open or create some file.

**Comment by mocap3069** [comment]
I changed the entire novacoin and .novacoin folders to have 777 permissions with the user and still get the same exact error? Any other folder this command would write to?

**Comment by Novakid556** [comment]
Google it

**Comment by mocap3069** [comment]
Google says this is a program issue? How do I fix a programming issue? 
Looks like a permission issue for the shared memory. It should not terminate the program?

**Comment by CryptoManiac** [comment]
@mocap3069 

>> I changed the entire novacoin and .novacoin folders to have 777 permissions with the user and still get the same exact error? 

Setting 777 is not a good idea. Better to ensure that all files and subdirectories are owned by right user and group. Try to run chown -R username:usergroup ~/.novacoin.

>> Any other folder this command would write to?

No, the only affected directory for novacoind is ~/.novacoin. You can try to change data directory path and see what happens. Or, maybe, it will be simpler to remove the directory and let the daemon to recreate it. But it's recommended to make a backup of course.
