### ISSUE TITLE
having two or more corresponding or identical height and hash , can any one resolve this ?

### ISSUE THREAD

**Issue by suryapratap1** [novacoin-project/novacoin#380]
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)
00000000000ef27a08025d1184dd9ad59ae5fdf97ed15b72ec7f11a28f99951f (pos)

**Comment by CryptoManiac** [comment]
Could you disclose additional details about issue and the context which lead you to problem?
