### ISSUE TITLE
allocators.h:23:10: fatal error: Windows.h: No such file or directory linux

### ISSUE THREAD

**Issue by awaissakhi11** [novacoin-project/novacoin#382]
make -j 3 CROSS=i686-w64-mingw32.static --f makefile.mingw i cross compiling bitcoin fork coin i am facing fatal error: Windows.h: No such file or directory is error . help me to resolve this issue . i am cross compiling this on ubuntu.

**Comment by CryptoManiac** [comment]
Hi. Looks like something went wrong with either development packages or include paths.
Have you tried to ensure that this header is present and accessible to compiler?

**Comment by awaissakhi11** [comment]
hi this issue is solved thanks you
