### ISSUE TITLE
Upgrade OpenSSL version

### ISSUE THREAD

**Issue by ilsawa** [novacoin-project/novacoin#385]
Когда свершится?
Ибо на последних версиях имеем:

bignum.h:50:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
И т.д.

Это на vertcoin решение
https://github.com/vertcoin-project/vertcoin-core/commit/5522e0ce9c9070ae8c536a8366e5a5d0316ca48d

**Comment by CryptoManiac** [comment]
Fixed
