### ISSUE TITLE
Adding BIP65 support

### ISSUE THREAD

**Issue by WikiMin3R** [novacoin-project/novacoin#390]
AtomicDEX integration requires working BIP65 implementation. 
This will greatly enhance Novacoin's ability to provide function, portability, and value well into the future!

See: https://en.bitcoin.it/wiki/BIP_0065

**Comment by CryptoManiac** [comment]
It is already supported.

```
static const unsigned int CHECKLOCKTIMEVERIFY_SWITCH_TIME = 1461110400; // Wednesday, 20-Apr-16 00:00:00 UTC
```
